import type { CategoryId, PairDifficulty, WordPair } from "@/types";

type PairSeed = readonly [
  primary: string,
  secondary: string,
  category: CategoryId,
  difficulty: PairDifficulty,
];

/**
 * Curated related pairs for "Unknown imposter" mode.
 *
 * Rules used while curating:
 *  - both words must be instantly recognisable
 *  - the pair must share a context so the imposter can bluff for a round or two
 *  - but they must differ in at least one obvious detail so good questions expose them
 */
const PAIR_SEEDS: PairSeed[] = [
  // ---------------------------------------------------------------- food
  ["Pizza", "Burger", "food", "easy"],
  ["Burger", "Hot Dog", "food", "easy"],
  ["Sandwich", "Wrap", "food", "easy"],
  ["Pasta", "Noodles", "food", "easy"],
  ["Spaghetti", "Lasagna", "food", "medium"],
  ["Sushi", "Dumplings", "food", "medium"],
  ["Taco", "Burrito", "food", "easy"],
  ["Fries", "Crisps", "food", "easy"],
  ["Rice", "Bread", "food", "easy"],
  ["Soup", "Stew", "food", "medium"],
  ["Salad", "Sandwich", "food", "medium"],
  ["Bacon", "Sausage", "food", "easy"],
  ["Steak", "Roast Chicken", "food", "medium"],
  ["Pancakes", "Waffles", "food", "easy"],
  ["Toast", "Bagel", "food", "easy"],
  ["Cereal", "Oatmeal", "food", "easy"],
  ["Omelette", "Fried Egg", "food", "easy"],
  ["Curry", "Chili", "food", "medium"],
  ["Ramen", "Pho", "food", "medium"],
  ["Popcorn", "Pretzel", "food", "medium"],
  ["Cheese", "Butter", "food", "easy"],
  ["Ketchup", "Mustard", "food", "easy"],
  ["Salt", "Sugar", "food", "easy"],
  ["Honey", "Jam", "food", "easy"],
  ["Fish and Chips", "Fried Chicken", "food", "medium"],
  ["Nachos", "Popcorn", "food", "medium"],
  ["Spring Roll", "Samosa", "food", "medium"],
  ["Falafel", "Meatballs", "food", "medium"],
  ["Hummus", "Guacamole", "food", "medium"],
  ["Kebab", "Shawarma", "food", "easy"],
  ["Biryani", "Fried Rice", "food", "medium"],
  ["Barbecue", "Picnic", "food", "easy"],
  ["Breakfast", "Brunch", "food", "easy"],
  ["Gravy", "Sauce", "food", "medium"],
  ["Turkey", "Roast Chicken", "food", "medium"],
  ["Tuna", "Salmon", "food", "easy"],
  ["Shrimp", "Crab", "food", "easy"],
  ["Tofu", "Cheese", "food", "hard"],
  ["Croissant", "Muffin", "food", "easy"],
  ["Garlic Bread", "Breadsticks", "food", "easy"],
  ["Granola", "Cereal", "food", "easy"],

  // ------------------------------------------------------------ fruits/veg
  ["Apple", "Pear", "fruits-veg", "easy"],
  ["Orange", "Lemon", "fruits-veg", "easy"],
  ["Lemon", "Lime", "fruits-veg", "easy"],
  ["Banana", "Mango", "fruits-veg", "medium"],
  ["Strawberry", "Raspberry", "fruits-veg", "easy"],
  ["Blueberry", "Cherry", "fruits-veg", "medium"],
  ["Watermelon", "Melon", "fruits-veg", "easy"],
  ["Pineapple", "Coconut", "fruits-veg", "medium"],
  ["Peach", "Apricot", "fruits-veg", "medium"],
  ["Grapes", "Raisins", "fruits-veg", "easy"],
  ["Carrot", "Potato", "fruits-veg", "easy"],
  ["Potato", "Sweet Potato", "fruits-veg", "easy"],
  ["Tomato", "Pepper", "fruits-veg", "medium"],
  ["Onion", "Garlic", "fruits-veg", "easy"],
  ["Broccoli", "Cauliflower", "fruits-veg", "easy"],
  ["Lettuce", "Cabbage", "fruits-veg", "medium"],
  ["Cucumber", "Zucchini", "fruits-veg", "medium"],
  ["Mushroom", "Eggplant", "fruits-veg", "hard"],
  ["Peas", "Corn", "fruits-veg", "easy"],
  ["Pumpkin", "Watermelon", "fruits-veg", "medium"],
  ["Avocado", "Banana", "fruits-veg", "hard"],
  ["Ginger", "Chili Pepper", "fruits-veg", "medium"],
  ["Celery", "Cucumber", "fruits-veg", "medium"],
  ["Beetroot", "Radish", "fruits-veg", "hard"],
  ["Kiwi", "Fig", "fruits-veg", "hard"],

  // -------------------------------------------------------------- desserts
  ["Ice Cream", "Cake", "desserts", "easy"],
  ["Cake", "Cupcake", "desserts", "easy"],
  ["Cookie", "Brownie", "desserts", "easy"],
  ["Doughnut", "Bagel", "desserts", "medium"],
  ["Chocolate", "Candy", "desserts", "easy"],
  ["Lollipop", "Chewing Gum", "desserts", "easy"],
  ["Cheesecake", "Apple Pie", "desserts", "medium"],
  ["Milkshake", "Smoothie", "desserts", "easy"],
  ["Marshmallow", "Cotton Candy", "desserts", "medium"],
  ["Caramel", "Toffee", "desserts", "medium"],
  ["Jelly", "Pudding", "desserts", "easy"],
  ["Popsicle", "Ice Cream", "desserts", "easy"],
  ["Muffin", "Cupcake", "desserts", "medium"],
  ["Churros", "Doughnut", "desserts", "medium"],
  ["Tiramisu", "Cheesecake", "desserts", "hard"],
  ["Cinnamon Roll", "Croissant", "desserts", "medium"],
  ["Baklava", "Mochi", "desserts", "hard"],
  ["Sundae", "Milkshake", "desserts", "easy"],

  // ---------------------------------------------------------------- drinks
  ["Coffee", "Tea", "drinks", "easy"],
  ["Tea", "Hot Chocolate", "drinks", "easy"],
  ["Orange Juice", "Apple Juice", "drinks", "easy"],
  ["Lemonade", "Iced Tea", "drinks", "easy"],
  ["Milk", "Milkshake", "drinks", "easy"],
  ["Soda", "Energy Drink", "drinks", "easy"],
  ["Latte", "Cappuccino", "drinks", "medium"],
  ["Espresso", "Iced Coffee", "drinks", "medium"],
  ["Bubble Tea", "Milkshake", "drinks", "medium"],
  ["Smoothie", "Juice", "drinks", "easy"],
  ["Slushie", "Popsicle", "drinks", "medium"],
  ["Chai", "Matcha", "drinks", "hard"],
  ["Mug", "Glass", "drinks", "easy"],
  ["Vending Machine", "Fridge", "drinks", "medium"],

  // --------------------------------------------------------------- animals
  ["Dog", "Cat", "animals", "easy"],
  ["Puppy", "Kitten", "animals", "easy"],
  ["Horse", "Donkey", "animals", "easy"],
  ["Horse", "Pony", "animals", "medium"],
  ["Cow", "Sheep", "animals", "easy"],
  ["Sheep", "Goat", "animals", "easy"],
  ["Pig", "Cow", "animals", "easy"],
  ["Chicken", "Duck", "animals", "easy"],
  ["Duck", "Swan", "animals", "easy"],
  ["Rabbit", "Hamster", "animals", "easy"],
  ["Mouse", "Rat", "animals", "easy"],
  ["Lion", "Tiger", "animals", "easy"],
  ["Tiger", "Leopard", "animals", "medium"],
  ["Leopard", "Cheetah", "animals", "medium"],
  ["Elephant", "Rhino", "animals", "medium"],
  ["Giraffe", "Zebra", "animals", "easy"],
  ["Monkey", "Gorilla", "animals", "easy"],
  ["Bear", "Polar Bear", "animals", "easy"],
  ["Panda", "Koala", "animals", "medium"],
  ["Wolf", "Fox", "animals", "easy"],
  ["Deer", "Antelope", "animals", "medium"],
  ["Squirrel", "Hedgehog", "animals", "medium"],
  ["Bat", "Owl", "animals", "medium"],
  ["Eagle", "Hawk", "animals", "medium"],
  ["Penguin", "Seal", "animals", "medium"],
  ["Parrot", "Peacock", "animals", "medium"],
  ["Flamingo", "Ostrich", "animals", "medium"],
  ["Pigeon", "Seagull", "animals", "easy"],
  ["Crow", "Sparrow", "animals", "medium"],
  ["Fish", "Shark", "animals", "easy"],
  ["Dolphin", "Whale", "animals", "easy"],
  ["Octopus", "Jellyfish", "animals", "medium"],
  ["Crab", "Lobster", "animals", "easy"],
  ["Turtle", "Snail", "animals", "medium"],
  ["Frog", "Lizard", "animals", "easy"],
  ["Snake", "Crocodile", "animals", "medium"],
  ["Spider", "Ant", "animals", "easy"],
  ["Bee", "Butterfly", "animals", "easy"],
  ["Ladybug", "Bee", "animals", "medium"],
  ["Mosquito", "Fly", "animals", "easy"],
  ["Worm", "Snail", "animals", "easy"],
  ["Kangaroo", "Koala", "animals", "medium"],
  ["Camel", "Horse", "animals", "medium"],
  ["Hippo", "Rhino", "animals", "medium"],
  ["Walrus", "Seal", "animals", "medium"],
  ["Sloth", "Koala", "animals", "hard"],
  ["Raccoon", "Skunk", "animals", "medium"],
  ["Goldfish", "Hamster", "animals", "medium"],
  ["Dinosaur", "Dragon", "animals", "medium"],
  ["Unicorn", "Dragon", "animals", "medium"],

  // ---------------------------------------------------------------- places
  ["Beach", "Swimming Pool", "places", "easy"],
  ["Park", "Garden", "places", "easy"],
  ["School", "University", "places", "easy"],
  ["Hospital", "Pharmacy", "places", "medium"],
  ["Airport", "Train Station", "places", "easy"],
  ["Train Station", "Bus Stop", "places", "easy"],
  ["Supermarket", "Market", "places", "easy"],
  ["Restaurant", "Cafe", "places", "easy"],
  ["Cafe", "Bakery", "places", "easy"],
  ["Cinema", "Theatre", "places", "easy"],
  ["Library", "Bookstore", "places", "easy"],
  ["Museum", "Art Gallery", "places", "easy"],
  ["Zoo", "Aquarium", "places", "easy"],
  ["Gym", "Swimming Pool", "places", "medium"],
  ["Bank", "Post Office", "places", "medium"],
  ["Hotel", "Hostel", "places", "easy"],
  ["Church", "Temple", "places", "medium"],
  ["Stadium", "Arena", "places", "medium"],
  ["Farm", "Ranch", "places", "medium"],
  ["Forest", "Jungle", "places", "easy"],
  ["Mountain", "Hill", "places", "easy"],
  ["Desert", "Beach", "places", "medium"],
  ["Island", "Peninsula", "places", "hard"],
  ["Lake", "Pond", "places", "easy"],
  ["River", "Stream", "places", "easy"],
  ["Waterfall", "Fountain", "places", "medium"],
  ["Cave", "Tunnel", "places", "medium"],
  ["Bridge", "Tunnel", "places", "easy"],
  ["Petrol Station", "Car Park", "places", "medium"],
  ["Shopping Mall", "Market", "places", "easy"],
  ["Police Station", "Fire Station", "places", "easy"],
  ["Theme Park", "Carnival", "places", "easy"],
  ["Harbour", "Marina", "places", "medium"],
  ["Lighthouse", "Watchtower", "places", "medium"],
  ["Castle", "Palace", "places", "easy"],
  ["Bowling Alley", "Ice Rink", "places", "medium"],
];

const PAIR_SEEDS_2: PairSeed[] = [
  // ------------------------------------------------------------- countries
  ["Italy", "Spain", "countries", "easy"],
  ["France", "Germany", "countries", "easy"],
  ["Greece", "Turkey", "countries", "medium"],
  ["Portugal", "Spain", "countries", "easy"],
  ["Netherlands", "Belgium", "countries", "medium"],
  ["Sweden", "Norway", "countries", "easy"],
  ["Norway", "Finland", "countries", "medium"],
  ["Ireland", "Scotland", "countries", "easy"],
  ["England", "Ireland", "countries", "easy"],
  ["Switzerland", "Austria", "countries", "medium"],
  ["Russia", "China", "countries", "medium"],
  ["Japan", "South Korea", "countries", "easy"],
  ["China", "Japan", "countries", "easy"],
  ["India", "Pakistan", "countries", "easy"],
  ["Thailand", "Vietnam", "countries", "easy"],
  ["Egypt", "Morocco", "countries", "medium"],
  ["Kenya", "Ethiopia", "countries", "medium"],
  ["Nigeria", "Ghana", "countries", "medium"],
  ["Brazil", "Argentina", "countries", "easy"],
  ["Mexico", "Peru", "countries", "medium"],
  ["Canada", "America", "countries", "easy"],
  ["Australia", "New Zealand", "countries", "easy"],
  ["Iceland", "Greenland", "countries", "medium"],
  ["Cuba", "Jamaica", "countries", "easy"],
  ["Saudi Arabia", "Iran", "countries", "medium"],

  // ---------------------------------------------------------------- cities
  ["Paris", "London", "cities", "easy"],
  ["New York", "Los Angeles", "cities", "easy"],
  ["Tokyo", "Seoul", "cities", "easy"],
  ["Rome", "Athens", "cities", "easy"],
  ["Barcelona", "Madrid", "cities", "easy"],
  ["Berlin", "Vienna", "cities", "medium"],
  ["Amsterdam", "Copenhagen", "cities", "medium"],
  ["Venice", "Amsterdam", "cities", "medium"],
  ["Istanbul", "Cairo", "cities", "medium"],
  ["Sydney", "Melbourne", "cities", "easy"],
  ["Las Vegas", "Los Angeles", "cities", "easy"],
  ["Toronto", "Chicago", "cities", "medium"],
  ["Mumbai", "Delhi", "cities", "easy"],

  // ---------------------------------------------------------------- nature
  ["Tree", "Flower", "nature", "easy"],
  ["Grass", "Moss", "nature", "medium"],
  ["Leaf", "Petal", "nature", "medium"],
  ["Rock", "Pebble", "nature", "easy"],
  ["Sand", "Soil", "nature", "easy"],
  ["Ocean", "Lake", "nature", "easy"],
  ["Sun", "Moon", "nature", "easy"],
  ["Star", "Moon", "nature", "easy"],
  ["Cloud", "Fog", "nature", "medium"],
  ["Rainbow", "Sunset", "nature", "medium"],
  ["Valley", "Canyon", "nature", "medium"],
  ["Volcano", "Earthquake", "nature", "medium"],
  ["Glacier", "Iceberg", "nature", "medium"],
  ["Cactus", "Palm Tree", "nature", "medium"],
  ["Rose", "Tulip", "nature", "easy"],
  ["Sunflower", "Daisy", "nature", "easy"],
  ["Bamboo", "Sugarcane", "nature", "hard"],
  ["Seed", "Root", "nature", "medium"],
  ["Mud", "Dust", "nature", "medium"],
  ["Sunrise", "Sunset", "nature", "easy"],
  ["Spring", "Autumn", "nature", "easy"],
  ["Winter", "Summer", "nature", "easy"],
  ["Seashell", "Starfish", "nature", "easy"],

  // --------------------------------------------------------------- weather
  ["Rain", "Snow", "weather", "easy"],
  ["Thunder", "Lightning", "weather", "easy"],
  ["Storm", "Hurricane", "weather", "medium"],
  ["Tornado", "Hurricane", "weather", "medium"],
  ["Wind", "Breeze", "weather", "easy"],
  ["Sunshine", "Heatwave", "weather", "easy"],
  ["Frost", "Ice", "weather", "easy"],
  ["Fog", "Mist", "weather", "easy"],
  ["Drizzle", "Downpour", "weather", "easy"],
  ["Flood", "Drought", "weather", "medium"],
  ["Umbrella", "Raincoat", "weather", "easy"],
  ["Blizzard", "Sandstorm", "weather", "medium"],
  ["Puddle", "Snowdrift", "weather", "medium"],

  // ---------------------------------------------------------------- sports
  ["Football", "Cricket", "sports", "easy"],
  ["Football", "Rugby", "sports", "easy"],
  ["Basketball", "Volleyball", "sports", "easy"],
  ["Tennis", "Badminton", "sports", "easy"],
  ["Table Tennis", "Tennis", "sports", "easy"],
  ["Baseball", "Cricket", "sports", "medium"],
  ["Golf", "Mini Golf", "sports", "medium"],
  ["Swimming", "Diving", "sports", "easy"],
  ["Running", "Cycling", "sports", "easy"],
  ["Boxing", "Wrestling", "sports", "easy"],
  ["Karate", "Judo", "sports", "easy"],
  ["Skiing", "Snowboarding", "sports", "easy"],
  ["Surfing", "Skateboarding", "sports", "medium"],
  ["Climbing", "Hiking", "sports", "easy"],
  ["Gymnastics", "Ballet", "sports", "medium"],
  ["Rowing", "Sailing", "sports", "easy"],
  ["Fishing", "Hunting", "sports", "medium"],
  ["Archery", "Darts", "sports", "medium"],
  ["Fencing", "Boxing", "sports", "medium"],
  ["Horse Riding", "Cycling", "sports", "medium"],
  ["Yoga", "Pilates", "sports", "medium"],
  ["Weightlifting", "Bodybuilding", "sports", "medium"],
  ["Bowling", "Snooker", "sports", "medium"],
  ["Olympics", "World Cup", "sports", "easy"],
  ["Referee", "Coach", "sports", "easy"],
  ["Trophy", "Medal", "sports", "easy"],

  // ---------------------------------------------------------------- school
  ["Homework", "Exam", "school", "easy"],
  ["Teacher", "Student", "school", "easy"],
  ["Pencil", "Pen", "school", "easy"],
  ["Eraser", "Sharpener", "school", "easy"],
  ["Notebook", "Textbook", "school", "easy"],
  ["Backpack", "Lunchbox", "school", "easy"],
  ["Whiteboard", "Chalk", "school", "medium"],
  ["Ruler", "Calculator", "school", "medium"],
  ["School Bus", "Uniform", "school", "medium"],
  ["Report Card", "Graduation", "school", "medium"],
  ["Mathematics", "Physics", "school", "easy"],
  ["History", "Geography", "school", "easy"],
  ["Chemistry", "Biology", "school", "easy"],
  ["Principal", "Teacher", "school", "easy"],
  ["Cafeteria", "Locker", "school", "medium"],

  // ------------------------------------------------------------ technology
  ["Internet", "Wifi", "technology", "easy"],
  ["Email", "Text Message", "technology", "easy"],
  ["Website", "App", "technology", "easy"],
  ["Emoji", "Sticker", "technology", "easy"],
  ["Battery", "Charger", "technology", "easy"],
  ["Bluetooth", "Wifi", "technology", "easy"],
  ["QR Code", "Barcode", "technology", "easy"],
  ["Robot", "Drone", "technology", "easy"],
  ["Virtual Reality", "Cinema", "technology", "medium"],

  // ----------------------------------------------------------- electronics
  ["Phone", "Tablet", "electronics", "easy"],
  ["Television", "Projector", "electronics", "easy"],
  ["Headphones", "Earbuds", "electronics", "easy"],
  ["Speaker", "Radio", "electronics", "easy"],
  ["Camera", "Phone", "electronics", "medium"],
  ["Keyboard", "Mouse", "electronics", "easy"],
  ["Printer", "Scanner", "electronics", "easy"],
  ["Router", "Modem", "electronics", "medium"],
  ["Microwave", "Oven", "electronics", "easy"],
  ["Refrigerator", "Freezer", "electronics", "easy"],
  ["Washing Machine", "Dishwasher", "electronics", "easy"],
  ["Vacuum Cleaner", "Mop", "electronics", "medium"],
  ["Hair Dryer", "Straightener", "electronics", "easy"],
  ["Fan", "Air Conditioner", "electronics", "easy"],
  ["Heater", "Fireplace", "electronics", "medium"],
  ["Torch", "Candle", "electronics", "medium"],
  ["Alarm Clock", "Watch", "electronics", "easy"],
  ["Toaster", "Kettle", "electronics", "easy"],
  ["Microwave", "Toaster", "electronics", "easy"],
  ["Light Bulb", "Lamp", "electronics", "easy"],
];

const PAIR_SEEDS_3: PairSeed[] = [
  // -------------------------------------------------------- transportation
  ["Car", "Motorcycle", "transportation", "easy"],
  ["Bus", "Train", "transportation", "easy"],
  ["Train", "Tram", "transportation", "easy"],
  ["Subway", "Train", "transportation", "easy"],
  ["Airplane", "Helicopter", "transportation", "easy"],
  ["Bicycle", "Scooter", "transportation", "easy"],
  ["Skateboard", "Rollerblades", "transportation", "easy"],
  ["Taxi", "Bus", "transportation", "easy"],
  ["Truck", "Van", "transportation", "easy"],
  ["Boat", "Ship", "transportation", "easy"],
  ["Submarine", "Ship", "transportation", "medium"],
  ["Hot Air Balloon", "Helicopter", "transportation", "medium"],
  ["Ambulance", "Fire Engine", "transportation", "easy"],
  ["Police Car", "Ambulance", "transportation", "easy"],
  ["Tractor", "Bulldozer", "transportation", "easy"],
  ["Crane", "Forklift", "transportation", "medium"],
  ["Canoe", "Kayak", "transportation", "easy"],
  ["Jet Ski", "Speedboat", "transportation", "easy"],
  ["Rocket", "Space Shuttle", "transportation", "easy"],
  ["Sled", "Sleigh", "transportation", "easy"],
  ["Roundabout", "Crossroads", "transportation", "medium"],
  ["Seatbelt", "Helmet", "transportation", "medium"],
  ["Steering Wheel", "Handlebars", "transportation", "medium"],
  ["Suitcase", "Backpack", "transportation", "easy"],
  ["Passport", "Ticket", "transportation", "easy"],

  // ------------------------------------------------------------------ jobs
  ["Doctor", "Nurse", "jobs", "easy"],
  ["Doctor", "Dentist", "jobs", "easy"],
  ["Teacher", "Professor", "jobs", "easy"],
  ["Firefighter", "Police Officer", "jobs", "easy"],
  ["Chef", "Waiter", "jobs", "easy"],
  ["Chef", "Baker", "jobs", "easy"],
  ["Barista", "Bartender", "jobs", "easy"],
  ["Farmer", "Gardener", "jobs", "easy"],
  ["Pilot", "Flight Attendant", "jobs", "easy"],
  ["Bus Driver", "Taxi Driver", "jobs", "easy"],
  ["Mechanic", "Electrician", "jobs", "medium"],
  ["Plumber", "Carpenter", "jobs", "medium"],
  ["Builder", "Architect", "jobs", "medium"],
  ["Engineer", "Scientist", "jobs", "medium"],
  ["Programmer", "Designer", "jobs", "medium"],
  ["Photographer", "Journalist", "jobs", "medium"],
  ["Actor", "Singer", "jobs", "easy"],
  ["Musician", "Dancer", "jobs", "easy"],
  ["Artist", "Writer", "jobs", "easy"],
  ["Lawyer", "Judge", "jobs", "easy"],
  ["Accountant", "Banker", "jobs", "medium"],
  ["Cashier", "Shop Assistant", "jobs", "easy"],
  ["Hairdresser", "Barber", "jobs", "easy"],
  ["Postman", "Delivery Driver", "jobs", "easy"],
  ["Vet", "Zookeeper", "jobs", "easy"],
  ["Lifeguard", "Security Guard", "jobs", "medium"],
  ["Astronaut", "Pilot", "jobs", "medium"],
  ["Soldier", "Sailor", "jobs", "medium"],
  ["Tour Guide", "Receptionist", "jobs", "medium"],

  // -------------------------------------------------------------- clothing
  ["T-Shirt", "Shirt", "clothing", "easy"],
  ["Hoodie", "Sweater", "clothing", "easy"],
  ["Jacket", "Coat", "clothing", "easy"],
  ["Jeans", "Trousers", "clothing", "easy"],
  ["Shorts", "Skirt", "clothing", "easy"],
  ["Dress", "Suit", "clothing", "easy"],
  ["Socks", "Gloves", "clothing", "medium"],
  ["Shoes", "Trainers", "clothing", "easy"],
  ["Boots", "Sandals", "clothing", "easy"],
  ["Flip Flops", "Slippers", "clothing", "easy"],
  ["High Heels", "Trainers", "clothing", "easy"],
  ["Hat", "Cap", "clothing", "easy"],
  ["Scarf", "Tie", "clothing", "medium"],
  ["Belt", "Braces", "clothing", "medium"],
  ["Swimsuit", "Wetsuit", "clothing", "easy"],
  ["Handbag", "Backpack", "clothing", "easy"],
  ["Wallet", "Purse", "clothing", "easy"],
  ["Watch", "Bracelet", "clothing", "easy"],
  ["Necklace", "Earrings", "clothing", "easy"],
  ["Ring", "Necklace", "clothing", "easy"],
  ["Helmet", "Cap", "clothing", "medium"],
  ["Apron", "Overalls", "clothing", "medium"],
  ["Uniform", "Costume", "clothing", "medium"],

  // ------------------------------------------------------------- household
  ["Sofa", "Armchair", "household", "easy"],
  ["Bed", "Sofa", "household", "easy"],
  ["Pillow", "Cushion", "household", "easy"],
  ["Blanket", "Duvet", "household", "easy"],
  ["Chair", "Stool", "household", "easy"],
  ["Table", "Desk", "household", "easy"],
  ["Bookshelf", "Cupboard", "household", "easy"],
  ["Mirror", "Window", "household", "medium"],
  ["Lamp", "Candle", "household", "easy"],
  ["Curtains", "Blinds", "household", "easy"],
  ["Carpet", "Rug", "household", "easy"],
  ["Clock", "Calendar", "household", "medium"],
  ["Vase", "Picture Frame", "household", "medium"],
  ["Doormat", "Rug", "household", "easy"],
  ["Bathtub", "Shower", "household", "easy"],
  ["Sink", "Bathtub", "household", "easy"],
  ["Towel", "Bathrobe", "household", "easy"],
  ["Soap", "Shampoo", "household", "easy"],
  ["Toothbrush", "Hairbrush", "household", "easy"],
  ["Broom", "Mop", "household", "easy"],
  ["Iron", "Hair Dryer", "household", "medium"],
  ["Radiator", "Fireplace", "household", "easy"],
  ["Staircase", "Ladder", "household", "medium"],

  // ------------------------------------------------------- everyday things
  ["Umbrella", "Sunhat", "everyday-objects", "medium"],
  ["Keys", "Wallet", "everyday-objects", "easy"],
  ["Book", "Magazine", "everyday-objects", "easy"],
  ["Newspaper", "Magazine", "everyday-objects", "easy"],
  ["Map", "Compass", "everyday-objects", "easy"],
  ["Paperclip", "Stapler", "everyday-objects", "easy"],
  ["Tape", "Glue", "everyday-objects", "easy"],
  ["Scissors", "Knife", "everyday-objects", "medium"],
  ["Envelope", "Stamp", "everyday-objects", "easy"],
  ["Matches", "Lighter", "everyday-objects", "easy"],
  ["Torch", "Lantern", "everyday-objects", "easy"],
  ["Comb", "Hairbrush", "everyday-objects", "easy"],
  ["Tissue", "Napkin", "everyday-objects", "easy"],
  ["Plaster", "Bandage", "everyday-objects", "easy"],
  ["Coin", "Banknote", "everyday-objects", "easy"],
  ["Hammer", "Screwdriver", "everyday-objects", "easy"],
  ["Nail", "Screw", "everyday-objects", "easy"],
  ["Rope", "Chain", "everyday-objects", "easy"],
  ["Ladder", "Stepstool", "everyday-objects", "easy"],
  ["Padlock", "Key", "everyday-objects", "easy"],

  // --------------------------------------------------------------- kitchen
  ["Fork", "Spoon", "kitchen", "easy"],
  ["Knife", "Fork", "kitchen", "easy"],
  ["Plate", "Bowl", "kitchen", "easy"],
  ["Cup", "Glass", "kitchen", "easy"],
  ["Pan", "Pot", "kitchen", "easy"],
  ["Frying Pan", "Baking Tray", "kitchen", "easy"],
  ["Chopping Board", "Tray", "kitchen", "medium"],
  ["Spatula", "Whisk", "kitchen", "easy"],
  ["Grater", "Peeler", "kitchen", "easy"],
  ["Can Opener", "Bottle Opener", "kitchen", "easy"],
  ["Colander", "Sieve", "kitchen", "easy"],
  ["Chopsticks", "Fork", "kitchen", "easy"],

  // ------------------------------------------------------------ activities
  ["Sleeping", "Napping", "activities", "easy"],
  ["Cooking", "Baking", "activities", "easy"],
  ["Cleaning", "Tidying", "activities", "easy"],
  ["Studying", "Working", "activities", "easy"],
  ["Reading", "Writing", "activities", "easy"],
  ["Singing", "Dancing", "activities", "easy"],
  ["Swimming", "Sunbathing", "activities", "easy"],
  ["Running", "Walking", "activities", "easy"],
  ["Camping", "Hiking", "activities", "easy"],
  ["Gardening", "Farming", "activities", "medium"],
  ["Painting", "Drawing", "activities", "easy"],
  ["Knitting", "Sewing", "activities", "easy"],
  ["Fishing", "Sailing", "activities", "medium"],
  ["Sleepover", "Road Trip", "activities", "medium"],

  // --------------------------------------------------------------- hobbies
  ["Photography", "Painting", "hobbies", "easy"],
  ["Chess", "Checkers", "hobbies", "easy"],
  ["Puzzles", "Crossword", "hobbies", "easy"],
  ["Board Games", "Card Games", "hobbies", "easy"],
  ["Origami", "Pottery", "hobbies", "medium"],
  ["Birdwatching", "Stargazing", "hobbies", "medium"],
  ["Martial Arts", "Yoga", "hobbies", "medium"],
  ["Woodworking", "DIY", "hobbies", "easy"],

  // ---------------------------------------------------------- entertainment
  ["Concert", "Festival", "entertainment", "easy"],
  ["Theatre", "Musical", "entertainment", "medium"],
  ["Fireworks", "Parade", "entertainment", "easy"],
  ["Roller Coaster", "Ferris Wheel", "entertainment", "easy"],
  ["Haunted House", "Escape Room", "entertainment", "medium"],
  ["Orchestra", "Choir", "entertainment", "easy"],
  ["Ballet", "Opera", "entertainment", "medium"],

  // ------------------------------------------------------------- movies/tv
  ["Action Movie", "Thriller", "movies-tv", "medium"],
  ["Comedy", "Sitcom", "movies-tv", "easy"],
  ["Superhero", "Science Fiction", "movies-tv", "medium"],
  ["Reality Show", "Game Show", "movies-tv", "easy"],
  ["Villain", "Hero", "movies-tv", "easy"],

  // ----------------------------------------------------------------- games
  ["Hide and Seek", "Tag", "games", "easy"],
  ["Monopoly", "Scrabble", "games", "easy"],
  ["Chess", "Dominoes", "games", "medium"],
  ["Jenga", "Dominoes", "games", "medium"],
  ["Poker", "Bingo", "games", "medium"],
  ["Darts", "Pool", "games", "easy"],
  ["Arcade", "Pinball", "games", "easy"],
  ["Sudoku", "Crossword", "games", "easy"],
  ["Charades", "Truth or Dare", "games", "easy"],
  ["Hopscotch", "Skipping Rope", "games", "easy"],
  ["Frisbee", "Kite", "games", "easy"],
  ["Laser Tag", "Paintball", "games", "easy"],
  ["Treasure Hunt", "Escape Room", "games", "medium"],

  // ---------------------------------------------------------------- travel
  ["Passport", "Boarding Pass", "transportation", "easy"],
  ["Souvenir", "Postcard", "transportation", "easy"],
  ["Cruise", "Ferry", "transportation", "easy"],
  ["Sunburn", "Sunscreen", "transportation", "easy"],

  // ------------------------------------------------------------- buildings
  ["Skyscraper", "Tower", "buildings", "easy"],
  ["House", "Apartment", "buildings", "easy"],
  ["Cottage", "Cabin", "buildings", "easy"],
  ["Mansion", "Palace", "buildings", "easy"],
  ["Tent", "Igloo", "buildings", "medium"],
  ["Castle", "Fort", "buildings", "easy"],
  ["Windmill", "Lighthouse", "buildings", "medium"],
  ["Barn", "Warehouse", "buildings", "medium"],
  ["Church", "Mosque", "buildings", "easy"],
  ["Prison", "Courthouse", "buildings", "medium"],
  ["Greenhouse", "Shed", "buildings", "easy"],
  ["Bridge", "Aqueduct", "buildings", "hard"],

  // ------------------------------------------------------------- festivals
  ["Christmas", "New Year", "festivals", "easy"],
  ["Halloween", "Carnival", "festivals", "easy"],
  ["Easter", "Christmas", "festivals", "easy"],
  ["Birthday", "Anniversary", "festivals", "easy"],
  ["Eid", "Thanksgiving", "festivals", "medium"],
  ["Valentine's Day", "Mother's Day", "festivals", "easy"],
  ["Baby Shower", "Housewarming", "festivals", "medium"],

  // -------------------------------------------------------------- outdoors
  ["Bench", "Picnic Table", "outdoors", "easy"],
  ["Streetlight", "Traffic Light", "outdoors", "easy"],
  ["Fence", "Hedge", "outdoors", "easy"],
  ["Swing", "Slide", "outdoors", "easy"],
  ["Lawnmower", "Hose", "outdoors", "easy"],
  ["Scarecrow", "Statue", "outdoors", "medium"],
  ["Fountain", "Pond", "outdoors", "easy"],

  // --------------------------------------------------------------- indoors
  ["Elevator", "Escalator", "household", "easy"],
  ["Fire Alarm", "Smoke Detector", "household", "easy"],
  ["Living Room", "Bedroom", "household", "easy"],
  ["Kitchen", "Dining Room", "household", "easy"],

  // ----------------------------------------------------------------- music
  ["Guitar", "Ukulele", "music", "easy"],
  ["Piano", "Keyboard", "music", "easy"],
  ["Drums", "Bongos", "music", "easy"],
  ["Violin", "Cello", "music", "easy"],
  ["Flute", "Clarinet", "music", "medium"],
  ["Trumpet", "Saxophone", "music", "easy"],
  ["Harp", "Piano", "music", "medium"],
  ["Microphone", "Speaker", "music", "easy"],
  ["Rock Music", "Pop Music", "music", "easy"],
  ["Jazz", "Blues", "music", "medium"],
  ["Hip Hop", "Reggae", "music", "medium"],
  ["Classical Music", "Opera", "music", "medium"],
  ["Choir", "Band", "music", "easy"],

  // --------------------------------------------------------- body & health
  ["Heart", "Brain", "body-health", "easy"],
  ["Eyes", "Ears", "body-health", "easy"],
  ["Nose", "Mouth", "body-health", "easy"],
  ["Teeth", "Tongue", "body-health", "easy"],
  ["Hands", "Feet", "body-health", "easy"],
  ["Knee", "Elbow", "body-health", "easy"],
  ["Sneeze", "Cough", "body-health", "easy"],
  ["Yawn", "Hiccups", "body-health", "easy"],
  ["Headache", "Fever", "body-health", "easy"],
  ["Cold", "Flu", "body-health", "easy"],

  // -------------------------------------------------------------- shopping
  ["Receipt", "Price Tag", "everyday-objects", "easy"],
  ["Cash", "Credit Card", "everyday-objects", "easy"],
  ["Gift Card", "Coupon", "everyday-objects", "easy"],

  // ----------------------------------------------------------------- space
  ["Astronaut", "Space Station", "space", "easy"],
  ["Rocket", "Satellite", "space", "easy"],
  ["Planet", "Star", "space", "easy"],
  ["Moon", "Earth", "space", "easy"],
  ["Mars", "Jupiter", "space", "easy"],
  ["Comet", "Meteor", "space", "easy"],
  ["Telescope", "Binoculars", "space", "easy"],
  ["Black Hole", "Galaxy", "space", "medium"],
  ["Alien", "Robot", "space", "easy"],
];

const ALL_SEEDS: PairSeed[] = [...PAIR_SEEDS, ...PAIR_SEEDS_2, ...PAIR_SEEDS_3];

export const WORD_PAIRS: WordPair[] = ALL_SEEDS.map(
  ([primary, secondary, category, difficulty]) => ({
    primary,
    secondary,
    category,
    difficulty,
  }),
);

const PAIRS_BY_CATEGORY = WORD_PAIRS.reduce<Map<CategoryId, WordPair[]>>((map, pair) => {
  const list = map.get(pair.category);
  if (list) list.push(pair);
  else map.set(pair.category, [pair]);
  return map;
}, new Map());

/**
 * Pairs available for the given category selection.
 * Falls back to the full set when the selection has no pairs of its own.
 */
export function getPairPool(categoryIds: CategoryId[]): WordPair[] {
  if (!categoryIds.length) return WORD_PAIRS;
  const pool = categoryIds.flatMap((id) => PAIRS_BY_CATEGORY.get(id) ?? []);
  return pool.length ? pool : WORD_PAIRS;
}

export const TOTAL_PAIR_COUNT = WORD_PAIRS.length;
